In [2]:
import pandas as pd

file_path = '/Users/zhaorunping/Desktop/Research_Onging/2410_LSE_Xue/result/241028bert+gpt_tales_topic_similarity.csv'
data = pd.read_csv(file_path)
data.head()

,文件路径,内容,与伪故事相似度
0,广西451/07771__080花山崖壁画.txt,080.花山崖壁画\n\n（壮族宁明县）\n\n左江明江悬崖峭壁上，古人画了许多朱红色的壁画...,0.755698
1,广西451/07980__185鸭子孵蛋.txt,185.鸭子孵蛋\n\n（瑶族大化县）\n\n鸡和鸭在一起，鸡总说鸭不会孵蛋，鸭很不服气。一...,0.596340
2,广西451/07722__054.歌师吴朝堂.txt,054.歌师吴朝堂\n\n(侗族三江县)\n\n有一天，传来一个消息：一去五年杳无音信的歌师...,0.704204
3,广西451/08079__236山鹰姑娘.txt,236.山鹰姑娘\n\n0么佬族罗城县）\n\n古时候，罗城县德音一带原是一片大森林。这里的...,0.696330
4,广西451/07696__041.卢天送射敌.txt,041.卢天送射敌\n\n（毛南族环江县）\n\n清朝道光年间，有一队官兵来到毛南山乡，他们...,0.670706

In [7]:
import matplotlib.pyplot as plt
import pandas as pd

# 筛选出包含“诚实”关键词的行和不包含“诚实”关键词的行
contains_honesty = data[data['内容'].str.contains('诚实', na=False)]
no_honesty = data[~data['内容'].str.contains('诚实', na=False)]

# 获取“与伪故事相似度”列数据
similarity_with_honesty = contains_honesty['与伪故事相似度']
similarity_without_honesty = no_honesty['与伪故事相似度']

In [10]:
# 计算分位数和均值
quantiles_with_honesty = contains_honesty['与伪故事相似度'].quantile([0, 0.25, 0.5, 0.75, 1])
quantiles_without_honesty = no_honesty['与伪故事相似度'].quantile([0, 0.25, 0.5, 0.75, 1])
mean_with_honesty = contains_honesty['与伪故事相似度'].mean()
mean_without_honesty = no_honesty['与伪故事相似度'].mean()

# 输出结果
print("包含“诚实”的分位数：")
print(quantiles_with_honesty)
print("均值:", mean_with_honesty)

print("\n不包含“诚实”的分位数：")
print(quantiles_without_honesty)
print("均值:", mean_without_honesty)

包含“诚实”的分位数：
0.00    0.537810
0.25    0.644241
0.50    0.679667
0.75    0.720430
1.00    0.840912
Name: 与伪故事相似度, dtype: float64
均值: 0.6816813833971292

不包含“诚实”的分位数：
0.00    0.440035
0.25    0.622932
0.50    0.657203
0.75    0.690902
1.00    0.833310
Name: 与伪故事相似度, dtype: float64
均值: 0.6565839347398772

In [11]:
from scipy.stats import ttest_ind
t_stat, p_value = ttest_ind(contains_honesty['与伪故事相似度'], no_honesty['与伪故事相似度'], equal_var=False)
print("\nT检验结果：")
print("t统计量:", t_stat)
print("p值:", p_value)

T检验结果：
t统计量: 7.189436171024874
p值: 1.0817246670271062e-11

In [12]:
file_path = '/Users/zhaorunping/Desktop/Research_Onging/2410_LSE_Xue/data/raw_data_tales/地图匹配_0426_v4.csv'
base = pd.read_csv(file_path)

base.head()

,rowid,name,cailu,provgb,citygb,cntygb,area,geocode,PROVGB_1953,CITYGB_1953,...,CITYGB_1990a,CNTYGB_1990a,PROVGB_2000,CITYGB_2000,CNTYGB_2000,PROVGB_2010,CITYGB_2010,CNTYGB_2010,new_name,area_group
0,1,04946__322老汉的宝物,missing values,missing valuesd,missing valuesd,missing valuesd,宁夏撒拉族循化貝,"{'lng': 116.413384, 'lat': 39.910925}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,老汉的宝物,宁夏
1,2,04743__121造过麦山的白土城,missing values,missing valuesd,missing valuesd,missing valuesd,宁夏土族民和县,"{'lng': 102.83639, 'lat': 36.325561}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,造过麦山的白土城,宁夏
2,3,05119__496伊斯玛悔过,林昌林,missing valuesd,missing valuesd,missing valuesd,宁夏回族西宁市,"{'lng': 101.78445, 'lat': 36.623385}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,伊斯玛悔过,宁夏
3,4,05049__425三姊妹,李友楼,missing valuesd,missing valuesd,missing valuesd,宁夏土族互助县,"{'lng': 101.964569, 'lat': 36.850022}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,三姊妹,宁夏
4,5,04849__225老鼠的智慧,missing values,missing valuesd,missing valuesd,missing valuesd,宁夏藏抜同仁县,"{'lng': 116.413384, 'lat': 39.910925}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,老鼠的智慧,宁夏

In [15]:
import re
# 将“与伪故事相似度”列与 base 表合并，依据 data 表的“文件名”和 base 表的“name”列
data['文件名'] = data['文件路径'].apply(lambda x: re.search(r'\/(.*?)\.txt', x).group(1) if re.search(r'\/(.*?)\.txt', x) else None)
merged_base = base.merge(data[['文件名', '与伪故事相似度']], left_on='name', right_on='文件名', how='left')
merged_base = merged_base.drop(columns=['文件名'])
merged_base.head()

,rowid,name,cailu,provgb,citygb,cntygb,area,geocode,PROVGB_1953,CITYGB_1953,...,CNTYGB_1990a,PROVGB_2000,CITYGB_2000,CNTYGB_2000,PROVGB_2010,CITYGB_2010,CNTYGB_2010,new_name,area_group,与伪故事相似度
0,1,04946__322老汉的宝物,missing values,missing valuesd,missing valuesd,missing valuesd,宁夏撒拉族循化貝,"{'lng': 116.413384, 'lat': 39.910925}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,老汉的宝物,宁夏,0.682252
1,2,04743__121造过麦山的白土城,missing values,missing valuesd,missing valuesd,missing valuesd,宁夏土族民和县,"{'lng': 102.83639, 'lat': 36.325561}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,造过麦山的白土城,宁夏,0.685242
2,3,05119__496伊斯玛悔过,林昌林,missing valuesd,missing valuesd,missing valuesd,宁夏回族西宁市,"{'lng': 101.78445, 'lat': 36.623385}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,伊斯玛悔过,宁夏,0.674774
3,4,05049__425三姊妹,李友楼,missing valuesd,missing valuesd,missing valuesd,宁夏土族互助县,"{'lng': 101.964569, 'lat': 36.850022}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,三姊妹,宁夏,0.668316
4,5,04849__225老鼠的智慧,missing values,missing valuesd,missing valuesd,missing valuesd,宁夏藏抜同仁县,"{'lng': 116.413384, 'lat': 39.910925}",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,老鼠的智慧,宁夏,0.654366

In [17]:
# 导出合并结果到 CSV 文件
output_path = '/Users/zhaorunping/Desktop/Research_Onging/2410_LSE_Xue/result/241029bert+gpt_tales_topic_similarity_merged.csv'
merged_base.to_csv(output_path, index=False, encoding='utf-8-sig')