In [1]:
import pandas as pd
file_path = '/Users/zhaorunping/Desktop/Research_Onging/2410_LSE_Xue/data/241202spatial_join_2010.xlsx'
df = pd.read_excel(file_path)
df.head()

,rowid,name,cailu,provgb,citygb,cntygb,area,geocode,PROVGB_1953,CITYGB_1953,...,PROVGB_2010,CITYGB_2010,CNTYGB_2010,new_name,area_group,centroid_1982,centroid_1990,centroid_2000,combined_centroid,matched_gbcode
0,1,04946__322老汉的宝物,missing values,missing valuesd,missing valuesd,missing valuesd,青海循化县,"{'lng': 116.413384, 'lat': 39.910925}",63.0,6301.0,...,NaN,NaN,NaN,老汉的宝物,宁夏,NaN,NaN,NaN,NaN,NaN
1,2,04743__121造过麦山的白土城,missing values,63,6321,632122,青海民和县,"{'lng': 102.83639, 'lat': 36.325561}",63.0,6301.0,...,NaN,NaN,632122.0,造过麦山的白土城,宁夏,POINT (102.76606258935416 36.14425184441833),POINT (102.76606258935416 36.14425184441833),NaN,POINT (102.76606258935416 36.14425184441833),632122.0
2,3,05119__496伊斯玛悔过,林昌林,63,6301,630100,青海西宁市,"{'lng': 101.78445, 'lat': 36.623385}",63.0,6301.0,...,NaN,NaN,630104.0,伊斯玛悔过,宁夏,POINT (101.75323508407594 36.63253767769244),POINT (101.75323508407588 36.632537677692405),NaN,POINT (101.75323508407591 36.632537677692426),630104.0
3,4,05049__425三姊妹,李友楼,missing valuesd,missing valuesd,missing valuesd,青海互助县,"{'lng': 101.964569, 'lat': 36.850022}",63.0,6301.0,...,NaN,NaN,NaN,三姊妹,宁夏,NaN,NaN,NaN,NaN,NaN
4,5,04849__225老鼠的智慧,missing values,63,6323,632321,青海同仁县,"{'lng': 116.413384, 'lat': 39.910925}",63.0,6323.0,...,NaN,NaN,632321.0,老鼠的智慧,宁夏,POINT (102.0739790147858 35.423843042544235),POINT (102.0739790147858 35.423843042544235),POINT (102.0739790147858 35.423843042544235),POINT (102.0739790147858 35.423843042544235),632321.0

In [2]:
import pandas as pd

# 文件路径
file_path = '/Users/zhaorunping/Desktop/Research_Onging/2410_LSE_Xue/data/241202spatial_join_2010.xlsx'

# 读取Excel文件
df = pd.read_excel(file_path)

# 定义筛选条件
def filter_rows(row):
    cntygb_1982 = row['CNTYGB_1982']
    cntygb_1990a = row['CNTYGB_1990a']
    cntygb_2000 = row['CNTYGB_2000']
    cntygb_2010 = row['CNTYGB_2010']

    # 非空值列表
    non_empty = [x for x in [cntygb_1982, cntygb_1990a, cntygb_2000] if pd.notna(x)]

    # 条件1：有一个非空，且和CNTYGB_2010不一致
    if len(non_empty) == 1 and non_empty[0] != cntygb_2010:
        return True

    # 条件2：两个非空，且两个中没有任意一个和CNTYGB_2010一样
    if len(non_empty) == 2 and all(x != cntygb_2010 for x in non_empty):
        return True

    # 条件3：三个非空，其中有两个是一样的，但是这个一样的和CNTYGB_2010不一样
    if len(non_empty) == 3:
        unique_values = set(non_empty)
        if len(unique_values) == 2 and cntygb_2010 not in unique_values:
            return True

    # 条件4：三个非空，三个都不一样，且没有任何一个和CNTYGB_2010一样
    if len(non_empty) == 3:
        unique_values = set(non_empty)
        if len(unique_values) == 3 and all(x != cntygb_2010 for x in unique_values):
            return True

    return False

# 应用筛选条件
filtered_df = df[df.apply(filter_rows, axis=1)]

In [5]:
filtered_df

,rowid,name,cailu,provgb,citygb,cntygb,area,geocode,PROVGB_1953,CITYGB_1953,...,PROVGB_2010,CITYGB_2010,CNTYGB_2010,new_name,area_group,centroid_1982,centroid_1990,centroid_2000,combined_centroid,matched_gbcode
2,3,05119__496伊斯玛悔过,林昌林,63,6301,630100,青海西宁市,"{'lng': 101.78445, 'lat': 36.623385}",63.0,6301.0,...,NaN,NaN,630104.0,伊斯玛悔过,宁夏,POINT (101.75323508407594 36.63253767769244),POINT (101.75323508407588 36.632537677692405),NaN,POINT (101.75323508407591 36.632537677692426),630104.0
8,9,07474__764.李起初讨批文,missing values,44,4453,445300,广东云浮县,"{'lng': 116.413384, 'lat': 39.910925}",44.0,4460.0,...,NaN,NaN,445323.0,李起初讨批文,广东,POINT (112.03235696284341 22.89331122735944),POINT (112.03235696284341 22.89331122735944),NaN,POINT (112.03235696284341 22.89331122735944),445323.0
10,11,05560__266.百米山,刘新平男36岁滁州市文化馆干部 1983年采束于滁州市,missing valuesd,missing valuesd,missing valuesd,安徽滁州市,"{'lng': 118.316264, 'lat': 32.303627}",NaN,NaN,...,NaN,NaN,341103.0,百米山,安徽,NaN,POINT (118.19710248004947 32.32068361333493),NaN,POINT (118.19710248004947 32.32068361333493),341103.0
11,12,05811__518.裁坊的剪子不带尖,张超凡 文化干部,missing valuesd,missing valuesd,missing valuesd,安徽亳州市,"{'lng': 115.782939, 'lat': 33.869338}",NaN,NaN,...,NaN,NaN,341602.0,裁坊的剪子不带尖,安徽,NaN,POINT (115.79696384968423 33.78075466799824),NaN,POINT (115.79696384968423 33.78075466799824),341602.0
13,14,05903__610.石匠的奇遇,鲁金普,34,3402,340200,安徽芜湖市,"{'lng': 118.376451, 'lat': 31.326319}",34.0,3401.0,...,NaN,NaN,340208.0,石匠的奇遇,安徽,POINT (118.37890843018972 31.388780779056756),POINT (118.37890843018974 31.388780779056752),POINT (118.52237805038544 31.185449440822353),POINT (118.42673163692162 31.321003666311952),340208.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17165,17166,16967_167燕子和家雀.txt,王泱烈K 43歹丈化干# 大淨爭* 采录时间，1985午9月4日,22,2202,220200,吉林吉林市,"{'lng': 126.55302, 'lat': 43.843577}",22.0,2201.0,...,NaN,NaN,220202.0,NaN,吉林,POINT (126.51505437118922 43.90832355386078),POINT (126.51505437118915 43.90832355386082),NaN,POINT (126.5150543711892 43.9083235538608),220202.0
17166,17167,16896_083朱雀山的传说.txt,w吕盛甘羿41 丈化干哪,22,2202,220200,吉林吉林市,"{'lng': 126.55302, 'lat': 43.843577}",22.0,2201.0,...,NaN,NaN,220202.0,NaN,吉林,POINT (126.51505437118922 43.90832355386078),POINT (126.51505437118915 43.90832355386082),NaN,POINT (126.5150543711892 43.9083235538608),220202.0
17167,17168,16934_128悬梁吊柱.txt,NaN,22,2202,220200,吉林吉林市,"{'lng': 126.55302, 'lat': 43.843577}",22.0,2201.0,...,NaN,NaN,220202.0,NaN,吉林,POINT (126.51505437118922 43.90832355386078),POINT (126.51505437118915 43.90832355386082),NaN,POINT (126.5150543711892 43.9083235538608),220202.0
17172,17173,16906_095洗.txt,李丈瑞女50罗丈化于标,22,2202,220200,吉林原吉林市郊区,missing values,22.0,2201.0,...,NaN,NaN,220202.0,NaN,吉林,POINT (126.51505437118922 43.90832355386078),POINT (126.51505437118915 43.90832355386082),NaN,POINT (126.5150543711892 43.9083235538608),220202.0
17226,17227,17276_542伙计李成.txt,NaN,22,2204,220422,吉林东辽县,"{'lng': 124.991995, 'lat': 42.927724}",NaN,NaN,...,NaN,NaN,220403.0,NaN,吉林,NaN,POINT (125.17394222485808 42.942739533819136),NaN,POINT (125.17394222485808 42.942739533819136),220403.0